Create satellite-dish-antenna.bas
mobluse/amateur-radio-electronics-c64 pull request #1
Opened 2024-11-23 05:05 UTC by N1OF

Fixed typos and bugs, working on physical C64

2024-11-28 22:03 UTC, mobluse commented on satellite-dish-antenna.bas
Thank you for your contribution!

260 G1 = (3.1415 * D) ↑ 2
should be
260 G1 = (3.1415 * D) ^ 2
This is because this should be ASCII in order to be automatically convertible to a C64 file. All ↑ in your files need to be ^. ^ looks like ↑ on the C64 screen.

270 G2 = 0.55 • Gl
should be
270 G2 = 0.55 * G1

570 IF H < 2 THEN GOTO 110
should be
570 IF H > 2 THEN GOTO 530
This is because the next line with ON takes care of the selection and this line is for trapping errors.

It would be good if you removed empty lines since there are no empty lines in the original.

Can you fix these things?

2024-11-28 22:17 UTC, mobluse requested changes
Thank you for your contribution!

About `satellite-dish-antenna.bas`:
`260 G1 = (3.1415 * D) ↑ 2`
should be
`260 G1 = (3.1415 * D) ^ 2`
This is because this should be ASCII in order to be automatically convertible to a C64 file. All ↑ in your files need to be ^. ^ looks like ↑ on the C64 screen.

`270 G2 = 0.55 • Gl`
should be
`270 G2 = 0.55 * G1`

`570 IF H < 2 THEN GOTO 110`
should be
`570 IF H > 2 THEN GOTO 530`
This is because the next line with ON takes care of the selection and this line is for trapping errors.

`670 PRINT "PRESS CR TO CONTINUE. . .`
should be
`670 PRINT "PRESS CR TO CONTINUE..."`

It would be good if you removed empty lines since there are no empty lines in the original.

Can you fix these things?

2024-12-01 17:07 UTC, N1OF reviewed
I believe the changes have been corrected and implemented, thank you!

2024-12-02 10:23 UTC, mobluse requested changes
There was no change. Maybe you forgot to commit your changes?

I discovered another error: In `vswr-calibrations.bas`
`570 PRINT "PROGRAM ENDED'`
should be
`570 PRINT "PROGRAM ENDED"`

2024-12-14 14:57 UTC, mobluse commented
I will merge it and fix the errors myself post merge.

2024-12-14 14:57 UTC, merged